### ISSUE TITLE
api.run('getcsvserver') returns TypeNotFound(content.node.qname())

### ISSUE THREAD

**Issue by ghost** [jathanism/netscaler-api#3]
When running the following I get, is this something that is resolvable?
Thanks.

> > > api.run('getcsvserver')
> > > not logged in; logging you in.
> > > Done

Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    api.run('getcsvserver')
  File "build\bdist.win32\egg\netscaler.py", line 170, in run
    resp = getattr(self.client.service, command)(**kwargs)
  File "build\bdist.win32\egg\suds\client.py", line 542, in **call**
    return client.invoke(args, kwargs)
  File "build\bdist.win32\egg\suds\client.py", line 602, in invoke
    result = self.send(soapenv)
  File "build\bdist.win32\egg\suds\client.py", line 643, in send
    result = self.succeeded(binding, reply.message)
  File "build\bdist.win32\egg\suds\client.py", line 678, in succeeded
    reply, result = binding.get_reply(self.method, reply)
  File "build\bdist.win32\egg\suds\bindings\binding.py", line 165, in get_reply
    result = unmarshaller.process(nodes[0], resolved)
  File "build\bdist.win32\egg\suds\umx\typed.py", line 66, in process
    return Core.process(self, content)
  File "build\bdist.win32\egg\suds\umx\core.py", line 48, in process
    return self.append(content)
  File "build\bdist.win32\egg\suds\umx\core.py", line 63, in append
    self.append_children(content)
  File "build\bdist.win32\egg\suds\umx\core.py", line 140, in append_children
    cval = self.append(cont)
  File "build\bdist.win32\egg\suds\umx\core.py", line 63, in append
    self.append_children(content)
  File "build\bdist.win32\egg\suds\umx\core.py", line 140, in append_children
    cval = self.append(cont)
  File "build\bdist.win32\egg\suds\umx\core.py", line 63, in append
    self.append_children(content)
  File "build\bdist.win32\egg\suds\umx\core.py", line 140, in append_children
    cval = self.append(cont)
  File "build\bdist.win32\egg\suds\umx\core.py", line 61, in append
    self.start(content)
  File "build\bdist.win32\egg\suds\umx\encoded.py", line 47, in start
    Typed.start(self, content)
  File "build\bdist.win32\egg\suds\umx\typed.py", line 80, in start
    raise TypeNotFound(content.node.qname())
TypeNotFound: Type not found: 'sc'

**Comment by ghost** [comment]
Issue closed, I was using a Netscaler Version 9.x WSDL to query a Version 10.x box
